APIKEY = "has-to-be-new-config-secret"
COHERE_KEY="has-to-be-new-config-secret"
ANTHROPIC_KEY="has-to-be-new-config-secret"
ATLASSRV = "has-to-be-new-config-secret"
AIPDB="has-to-be-new-config-secret"
ATLAS_PK="has-to-be-new-config-secret"
ATLAS_K="has-to-be-new-config-secret"
IDX_URL="has-to-be-new-config-secret"
